export const codeItDataActionTypes = {
    SET_CODES: 'SET_CODES',
    SET_KEYWORDS: 'SET_KEYWORDS',
    INCREASE_PROGRESS_LENGTH:"INCREASE_PROGRESS_LENGTH",
    DECREASE_PROGRESS_LENGTH:"DECREASE_PROGRESS_LENGTH",
    INCREASE_NUMBER_OF_INPUTS:"INCREASE_NUMBER_OF_INPUTS",
    DECREASE_NUMBER_OF_INPUTS:"DECREASE_NUMBER_OF_INPUTS",
    
};
  